/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author hebod
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    private DefaultTreeModel modelo;
    private DefaultMutableTreeNode nodoSeleccionado;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Teléfono");
        this.jTblPrimera.setModel(modeloTabla);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jArbol = new javax.swing.JTree();
        jBtnCargarModelos = new javax.swing.JButton();
        jTfTextoAgregado = new javax.swing.JTextField();
        jBtnInsertar = new javax.swing.JButton();
        jBtnEliminarNodo = new javax.swing.JButton();
        jTfNodoSeleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPrimera = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTfNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTfFila = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfColumna = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTfNuevoDato = new javax.swing.JTextField();
        jBtnInsertarEnTabla = new javax.swing.JButton();
        jBtnEliminarEnTabla = new javax.swing.JButton();
        jBtnEliminarTodoEnTabla = new javax.swing.JButton();
        jBtnModificarTodoEnTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPan1.setBackground(new java.awt.Color(204, 204, 255));

        jArbol.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jArbolValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jArbol);

        jBtnCargarModelos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnCargarModelos.setText("Cargar Modelos");
        jBtnCargarModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCargarModelosActionPerformed(evt);
            }
        });

        jTfTextoAgregado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jBtnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnInsertar.setText("Insertar");
        jBtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertarActionPerformed(evt);
            }
        });

        jBtnEliminarNodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnEliminarNodo.setText("Eliminar");
        jBtnEliminarNodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarNodoMouseClicked(evt);
            }
        });

        jTfNodoSeleccionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nodo Seleccionado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nodo Nuevo");

        jBtnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnModificar.setText("Modificar");
        jBtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnModificarMouseClicked(evt);
            }
        });

        jTblPrimera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblPrimera);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jTfNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");

        jTfApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Teléfono");

        jTfTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fila");

        jTfFila.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Columna");

        jTfColumna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Nuevo Dato");

        jTfNuevoDato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jBtnInsertarEnTabla.setText("Insertar");
        jBtnInsertarEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsertarEnTablaActionPerformed(evt);
            }
        });

        jBtnEliminarEnTabla.setText("Eliminar");
        jBtnEliminarEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarEnTablaActionPerformed(evt);
            }
        });

        jBtnEliminarTodoEnTabla.setText("Eliminar Todo");
        jBtnEliminarTodoEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarTodoEnTablaActionPerformed(evt);
            }
        });

        jBtnModificarTodoEnTabla.setText("Modificar");
        jBtnModificarTodoEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarTodoEnTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPan1Layout = new javax.swing.GroupLayout(jPan1);
        jPan1.setLayout(jPan1Layout);
        jPan1Layout.setHorizontalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBtnInsertar)
                        .addGap(139, 139, 139)
                        .addComponent(jBtnModificar)
                        .addContainerGap())
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jBtnCargarModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfTextoAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPan1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTfNombre))
                                    .addGroup(jPan1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTfApellido))
                                    .addGroup(jPan1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfTelefono))))
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnEliminarEnTabla)
                                    .addComponent(jBtnInsertarEnTabla))))
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnEliminarTodoEnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnModificarTodoEnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPan1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel1))
                                    .addGroup(jPan1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPan1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jBtnEliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTfNodoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPan1Layout.createSequentialGroup()
                                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTfFila, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                    .addComponent(jTfColumna)
                                                    .addComponent(jTfNuevoDato))))))
                                .addGap(0, 14, Short.MAX_VALUE))))))
        );
        jPan1Layout.setVerticalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCargarModelos)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTfNodoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEliminarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnModificar)
                                    .addComponent(jBtnInsertar)))
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfTextoAgregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTfFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTfColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTfNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnInsertarEnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnEliminarTodoEnTabla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnEliminarEnTabla)
                            .addComponent(jBtnModificarTodoEnTabla))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCargarModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCargarModelosActionPerformed
        modelo = new DefaultTreeModel(new DefaultMutableTreeNode("Raíz"));
        jArbol.setModel(modelo);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnCargarModelosActionPerformed

    private void jBtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertarActionPerformed
        String texto = this.jTfTextoAgregado.getText();
        DefaultMutableTreeNode n= new DefaultMutableTreeNode(texto);
        
        if(nodoSeleccionado!=null){
            modelo.insertNodeInto(n,nodoSeleccionado,nodoSeleccionado.getChildCount());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnInsertarActionPerformed

    private void jArbolValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jArbolValueChanged
        nodoSeleccionado=(DefaultMutableTreeNode) jArbol.getLastSelectedPathComponent();
        if(nodoSeleccionado!=null){
            jTfNodoSeleccionado.setText((String)nodoSeleccionado.getUserObject());
         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jArbolValueChanged

    private void jBtnEliminarNodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarNodoMouseClicked
        if(nodoSeleccionado!=null){
            modelo.removeNodeFromParent(nodoSeleccionado); 
        }    
    }//GEN-LAST:event_jBtnEliminarNodoMouseClicked

    private void jBtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnModificarMouseClicked
        if(nodoSeleccionado!=null){
            nodoSeleccionado.setUserObject(jTfNodoSeleccionado.getText());
            modelo.nodeChanged(nodoSeleccionado);
        }    
    }//GEN-LAST:event_jBtnModificarMouseClicked

    private void jBtnInsertarEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsertarEnTablaActionPerformed
        // TODO add your handling code here:
        String [] info = new String[3];
        info[0] = jTfNombre.getText();
        info[1] = jTfApellido.getText();
        info[2] = jTfTelefono.getText();
        modeloTabla.addRow(info);
        
        jTfNombre.setText("");
        jTfApellido.setText("");
        jTfTelefono.setText("");
    }//GEN-LAST:event_jBtnInsertarEnTablaActionPerformed

    private void jBtnEliminarEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarEnTablaActionPerformed
        // TODO add your handling code here:
        int fila=jTblPrimera.getSelectedRow();
        if(fila>=0){
            modeloTabla.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Selecionar fila");
        }
    }//GEN-LAST:event_jBtnEliminarEnTablaActionPerformed

    private void jBtnEliminarTodoEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarTodoEnTablaActionPerformed
        // TODO add your handling code here:
        int fila = jTblPrimera.getRowCount();
        for (int i=fila-1; i>=0; i--){
            modeloTabla.removeRow(i);
        }
    }//GEN-LAST:event_jBtnEliminarTodoEnTablaActionPerformed

    private void jBtnModificarTodoEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarTodoEnTablaActionPerformed
        // TODO add your handling code here:
        int fila = Integer.parseInt(jTfFila.getText());
        int columna = Integer.parseInt(jTfColumna.getText());
        modeloTabla.setValueAt(jTfNuevoDato.getText(),fila,columna);
        
    }//GEN-LAST:event_jBtnModificarTodoEnTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jArbol;
    private javax.swing.JButton jBtnCargarModelos;
    private javax.swing.JButton jBtnEliminarEnTabla;
    private javax.swing.JButton jBtnEliminarNodo;
    private javax.swing.JButton jBtnEliminarTodoEnTabla;
    private javax.swing.JButton jBtnInsertar;
    private javax.swing.JButton jBtnInsertarEnTabla;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnModificarTodoEnTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPan1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblPrimera;
    private javax.swing.JTextField jTfApellido;
    private javax.swing.JTextField jTfColumna;
    private javax.swing.JTextField jTfFila;
    private javax.swing.JTextField jTfNodoSeleccionado;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JTextField jTfNuevoDato;
    private javax.swing.JTextField jTfTelefono;
    private javax.swing.JTextField jTfTextoAgregado;
    // End of variables declaration//GEN-END:variables
}
